
proxy_cache_path /var/www/cache keys_zone=cache:16m inactive=365d min_free=4G max_size=32G;
proxy_cache_valid 365d;
proxy_cache_revalidate on;
proxy_cache_use_stale error timeout invalid_header updating http_403 http_404 http_429 http_500 http_502 http_503 http_504;

server {
    listen 80;
    listen [::]:80;
    server_name _;
    root /var/www/cache;
    
    proxy_next_upstream error timeout invalid_header http_403 http_404 http_429 http_500 http_502 http_503 http_504;
    proxy_store_access user:rw group:rw all:r;
    proxy_redirect off;

    location ~ \.(db|files)$ {
        return 404;
    }

    location ~ \.tar\.(xz|zst)(\.sig)?$ {
        proxy_pass http://$repo$request_uri;
        proxy_cache cache;
    }
}

map $request_uri $repo {
    default "";
    ~^/([^/]+)/os/[^/]+ $1;
}
