
proxy_cache_path /var/www/cache keys_zone=cache:16m inactive=$CACHE_TIMEOUT min_free=$CACHE_MIN_FREE max_size=$CACHE_MAX_SIZE;
proxy_cache_valid $CACHE_TIMEOUT;
proxy_cache_revalidate on;
proxy_cache_use_stale error timeout invalid_header updating http_403 http_404 http_429 http_500 http_502 http_503 http_504;

server {
    listen 80;
    listen [::]:80;
    server_name _;
    root /var/www/cache;
    
    proxy_next_upstream error timeout invalid_header http_403 http_404 http_429 http_500 http_502 http_503 http_504;
    proxy_store_access user:rw group:rw all:r;
    proxy_redirect off;
    proxy_connect_timeout $CONNECT_TIMEOUT;

    add_header_inherit merge;
    add_header X-Cache-Status $upstream_cache_status always;

    location ~ \.(db|files)$ {
        return 404;
    }

    location ~ \.tar\.(xz|zst)(\.sig)?$ {
        proxy_pass http://$repo$request_uri;
        proxy_cache cache;
        proxy_set_header Accept $accept;
    }
}

map $request_uri $repo {
    default "";
    ~^/([^/]+)/os/[^/]+ $1;
}

map $request_uri $accept {
    default */*;
    ~\.sig$ application/pgp-signature;
    ~\.zst$ application/zstd;
    ~\.xz$ application/x-xz;
}
