server {
    listen 80;
    listen [::]:80;
    server_name _;
    root /var/www/cache;
    
    proxy_next_upstream error timeout invalid_header http_403 http_404 http_429 http_500 http_502 http_503 http_504;
    proxy_store_access user:rw group:rw all:r;
    proxy_redirect off;

    location ~ /$ {
        autoindex on;
    }

    location ~ \.(db|files)$ {
        return 404;
    }

    location ~ \.tar\.(xz|zst)(\.sig)?$ {
        try_files $uri @upstream;
    }

    location @upstream {
        internal;
        proxy_pass http://$repo$request_uri;
        proxy_store on;
    }
}

map $request_uri $repo {
    default "";
    ~^/([^/]+)/os/[^/]+ $1;
}
